FROM python:3.8-slim-buster

WORKDIR /app

COPY ml/requirements.txt requirements.txt

RUN pip3 install -r requirements.txt

COPY ml/src src
COPY ml/resources resources

CMD [ "python3", "src/app.py"]
